CC=gcc -g

all: test1 testbad test_simple

test1: test1.c
	${CC} test1.c -o ../test1
testbad: testbad.c
	${CC} testbad.c -o ../testbad
test_simple: test_simple.c
	${CC} test_simple.c -o ../test_simple
